---

- hosts: localhost
  tasks:
    # this could be better
    # like don't hard code the user name
    # and other stuf
    - name: Make /home/dev/workspace
      become: true
      become_user: dev
      file:
        path: ~/workspace
        state: directory

    - include_tasks: "setup-{{ ansible_distribution }}.yml"

    - name: Clone dotfiles repo
      become: true
      become_user: dev
      git:
        repo: https://github.com/K-rangeR/dotfiles.git
        dest: ~/.dotfiles
        clone: yes
        update: yes

    - name: Stow dotfiles
      become: true
      become_user: dev
      shell:
        cmd: mv ~/.bashrc ~/.bashrc.back ; mv ~/.bash_profile ~/.bash_profile.back ; stow bash ; stow git ; stow tmux
        chdir: ~/.dotfiles

    - name: Source bashrc
      become: true
      become_user: dev
      shell:
        cmd: source ~/.bashrc
