---

- hosts: localhost
  become: true
  tasks:
    # this could be better
    # like don't hard code the user name
    - name: Make /home/dev/workspace
      file:
        path: /home/dev/workspace
        state: directory
        owner: dev
        group: dev

    - include_tasks: "setup-{{ ansible_distribution }}.yml"

    - name: Clone dotfiles repo
      git:
        repo: https://github.com/K-rangeR/dotfiles.git
        dest: /home/dev/.dotfiles
        clone: yes
        update: yes

    - name: Stow dotfiles
      shell:
        cmd: stow bash ; stow git ; stow tmux
        chdir: /home/dev/.dotfiles

